export enum ApiPathEnum {
  Login = "login",
  Register = "register",
  Logout = "logout",
  FindAll = "findAll",
  FindById = "find/",
  Create = "create",
  CreateAll = "createAll",
  Update = "update",
  Delete = "delete/",
  FindTaskByModul = "findTasksByModul/",
  FindAttachmentByTask = "findAttachmentsByTask/",
  DeleteAttachmentsById = "deleteAttachmentsById",
  FindModulsByClassroom = "findModulsByClassroom",
  FindModulsByCreator = "findModulsByCreator/",
  FindCommitmentsByUserAndModul = "findCommitmentsByUserAndModul/",
  DeleteCommitmentsById = "deleteCommitmentsById",
  FindTasksByIds = "findTasksByIds",
  FindUsersByClassroom = "findUsersByClassroom/",
  FindUsersByIds = "findUsersByIds",
  FindMessagesByParties = "findMessagesByParties/"
}
